#!/usr/bin/env sh
set -u
only_main=
. ${POSTSYNC_FUNCTIONS:-"${PORTAGE_CONFIGROOT-}"/etc/portage/repo.postsync.d/portage-postsyncd-mv.sh} \
	${1+"$@"}
git_repository || exit 0
restart_as_default "$@"

git_repack_days
[ -n "${git_repack_days:++}" ] || exit 0
set -- "$git_repack_days" .git/git-repack.date
! max_days_file "$@" || exit 0
git_repack . "Calling git-repack for the $repository_name repository" \
	&& update_days_file "$@"
