#!/usr/bin/env sh
set -u
only_main=+
. ${POSTSYNC_FUNCTIONS:-"${PORTAGE_CONFIGROOT-}"/etc/portage/repo.postsync.d/portage-postsyncd-mv.sh} \
	${1+"$@"}
is_git || exit 0
restart_as_default "$@"

timerump=/metadata/timestamp.x
timefile=$repository_path$timerump

fetch_timestamp() {
	postsync_sync
	ebeginl "Fetching metadata timestamp for the $repository_name repository"
	rsync_a -- "$POSTSYNC_SYNC$timerump" "$timefile"
	eend $?
}

fetch_cache() {
	postsync_sync
	ebeginl "Fetching pre-generated metadata for the $repository_name repository"
	fetch_cache=/metadata/md5-cache
	rsync_a ${POSTSYNC_RSYNC_EXTRA_OPTS--c} -- \
		"$POSTSYNC_SYNC$fetch_cache" "$repository_path$fetch_cache"
	eend $?
}

compare_list_sub() {
	for compare_list_i
	do	test -r "$compare_list_i" || continue
		compare_list=`stat -c '%Y' "$compare_list_i"` || continue
		is_number "$compare_list" || continue
		[ "$compare_list" -le "$max_days_file" ] || {
			einfo "Fetching metadata due to recent $compare_list_i"
			return 0
		}
	done
	return 1
}

compare_list() {
	: ${POSTSYNC_ECLASSES_MIN:=500}
	is_number "$POSTSYNC_ECLASSES_MIN" || POSTSYNC_ECLASSES_MIN=
	[ -z "${POSTSYNC_ECLASSES_MIN:++}" ] || \
		command -v eclasses.usage >/dev/null 2>&1 \
		|| POSTSYNC_ECLASSES_MIN=
	[ -n "${POSTSYNC_COMPARE_LIST:++}${POSTSYNC_ECLASSES_MIN:++}" ] \
		|| return
	[ -n "$max_days_file" ] || max_days_file 1 "$timefile" '' || return 0
	if [ -n "${POSTSYNC_COMPARE_LIST:++}" ]
	then	cd -- "$repository_path" >/dev/null 2>&1 || return
		case $- in
		*f*)
			set +f
			compare_list_sub $POSTSYNC_COMPARE_LIST
			compare_list_res=$?
			set -f
			[ $compare_list_res -ne 0 ] || return 0;;
		*)
			compare_list_sub $POSTSYNC_COMPARE_LIST || return 0;;
		esac
	fi
	[ -n "${POSTSYNC_ECLASSES_MIN:++}" ] || return
	ebegin 'Checking for recent eclasses changes'
	compare_list=`eclasses.usage -1 -o -d "$repository_path" \
		-t "$max_days_file" -m "$POSTSYNC_ECLASSES_MIN"` \
	eend $? || return
	[ -n "${compare_list:++}" ] || return
	einfo "Fetching metadata due to recent $compare_list.eclass"
	return 0
}

set -- "${POSTSYNC_DAYS_FETCH_CACHE:-2}" fetch-cache.date
! max_days_file "$@" || exit 0

! max_days_file "${POSTSYNC_DAYS_CACHE:-10}" "$timefile" || compare_list || {
	einfo "Skipping fetching of metadata for the $repository_name repository"
	exit 0
}
fetch_timestamp || exit 0
max_days_file "${POSTSYNC_DAYS_CACHE_MAX:-1}" "$timefile" || {
	ewarn "Not fetching metadata cache: $timefile unreasonably old"
	exit 0
}
fetch_cache

update_days_file "$@"
