#!/usr/bin/env sh
set -u
only_main=
. ${POSTSYNC_FUNCTIONS:-"${PORTAGE_CONFIGROOT-}"/etc/portage/repo.postsync.d/portage-postsyncd-mv.sh} \
	${1+"$@"}
! postsync_skip || exit 0
restart_as_default "$@"

[ x"$repository_name" != x"$POSTSYNC_MAIN_REPOSITORY" ] || if is_git
then	update_days_file 1 metadata/timestamp.x
else	exit 0
fi
egencache_options
call_egencache $egencache_options
