#!/usr/bin/env sh
# SPDX-License-Identifier: GPL-2.0-only
set -u
only_main=+
. ${POSTSYNC_FUNCTIONS:-"${PORTAGE_CONFIGROOT-}"/etc/portage/repo.postsync.d/portage-postsyncd-mv.sh} \
	${1+"$@"}
exit_if_mirror
is_git || exit 0
restart_as_default "$@"

set -- "${POSTSYNC_DAYS_GLSA:-2}" glsa.date metadata/glsa /.git
! max_days_file "$@" || exit 0
normalize_gitkeep POSTSYNC_KEEP_GLSA
git_clone -g $POSTSYNC_KEEP_GLSA -r "${POSTSYNC_RETRY_GLSA:-1}" -- \
	"${POSTSYNC_DEPTH_GLSA:-1}" \
	"${POSTSYNC_URL_GLSA:-https://anongit.gentoo.org/git/data/glsa.git}" \
	"$3" 'Updating GLSAs' && update_days_file "$@"
