#!/usr/bin/env sh
# SPDX-License-Identifier: GPL-2.0-only
set -u
only_main=+
. ${POSTSYNC_FUNCTIONS:-"${PORTAGE_CONFIGROOT-}"/etc/portage/repo.postsync.d/portage-postsyncd-mv.sh} \
	${1+"$@"}
exit_if_mirror
is_git || exit 0
restart_as_default "$@"

set -- "${POSTSYNC_DAYS_PROJECTS_XML:-30}" projects.xml.date \
	metadata/projects.xml
! max_days_file "$@" || exit 0
ebeginl 'Updating projects.xml'
wget ${PORTAGE_QUIET:+-q} -P "$repository_path/metadata/" -N \
	"${POSTSYNC_URL_PROJECTS_XML:-https://api.gentoo.org/metastructure/projects.xml}"
eend $? && update_days_file "$@"
