#!/usr/bin/env sh
set -u
qreinit=${PORTAGE_CONFIGROOT-}/etc/portage/repo.postsync.d/q-reinit
command -v q >/dev/null 2>&1 && ! test -x "$qreinit" || exit 0
only_main=
. ${POSTSYNC_FUNCTIONS:-"${PORTAGE_CONFIGROOT-}"/etc/portage/repo.postsync.d/portage-postsyncd-mv.sh} \
	${1+"$@"}
#restart_as_default "$@"
[ -n "${repository_name:++}" ] || exit 0
einfo "Calling q --reinitialize for the $repository_name repository"
q ${PORTAGE_QUIET:+-q} --reinitialize="${repository_path}"
eend $?
