#!/usr/bin/env sh
set -u
only_main=:
. ${POSTSYNC_FUNCTIONS:-"${EPREFIX-}"/lib/gentoo/repo.postsync.functions.sh} "$@"
case $sync_uri in
*.git)
	restart_as_default "$@";;
*)
	exit 0;;
esac

max_days_file "${POSTSYNC_DAYS_GIT_GC:-7}" git-gc.date || \
git_gc "$repository_path" "Calling git-gc for $repository_name repository"
