#!/usr/bin/env sh
set -u
only_main=
. ${POSTSYNC_FUNCTIONS:-"${EPREFIX-}"/etc/portage/repo.postsync.d/portage-postsyncd-mv.sh} \
	${1+"$@"}
git_repository || exit 0
restart_as_default "$@"

git_gc_days
[ -n "${git_gc_days:++}" ] || exit 0
set -- "$git_gc_days" .git/git-gc.date
! max_days_file "$@" || exit 0
git_gc . "Calling git-gc for the $repository_name repository" \
	&& update_days_file "$@"
