#!/usr/bin/env sh
set -u
only_main=-
. ${POSTSYNC_FUNCTIONS:-"${EPREFIX-}"/lib/gentoo/repo.postsync.functions.sh} \
	${1+"$@"}
is_git || exit 0
restart_as_default "$@"

git_gc "$repository_path" "Calling git-gc for the $repository_name repository"
