#!/usr/bin/env sh
set -u
only_main=+
. ${POSTSYNC_FUNCTIONS:-"${PORTAGE_CONFIGROOT-}"/etc/portage/repo.postsync.d/portage-postsyncd-mv.sh} \
	${1+"$@"}
is_git || exit 0
restart_as_default "$@"

timerump=/metadata/timestamp.x
timefile=$repository_path$timerump

fetch_timestamp() {
	postsync_sync
	ebegin "Fetching metadata timestamp for the $repository_name repository"
	rsync_a "$POSTSYNC_SYNC$timerump" "$timefile"
	eend $?
}

fetch_cache() {
	postsync_sync
	ebegin "Fetching pre-generated metadata for the $repository_name repository"
	fetch_cache=/metadata/md5-cache
	rsync_a "$POSTSYNC_SYNC$fetch_cache" "$repository_path$fetch_cache"
	eend $?
}

! max_days_file "${POSTSYNC_DAYS_CACHE:-10}" "$timefile" || {
	einfo "Skipping fetching of metadata for the $repository_name repository"
	exit 0
}
fetch_timestamp || exit 0
max_days_file "${POSTSYNC_DAYS_CACHE_MAX:-1}" "$timefile" || {
	ewarn "Not fetching metadata cache: $timefile unreasonably old"
	exit 0
}
fetch_cache
