#!/usr/bin/env sh
set -u
only_main=:
. ${POSTSYNC_FUNCTIONS:-"${EPREFIX-}"/lib/gentoo/repo.postsync.functions.sh} ${1+"$@"}
case $sync_uri in
*.git)
	restart_as_default "$@";;
*)
	exit 0;;
esac

max_days_file "${POSTSYNC_DAYS_NEWS:-1}" news.date || \
	git_clone -g "${POSTSYNC_DEPTH_NEWS:-1}" \
	"${POSTSYNC_URL_NEWS:-https://anongit.gentoo.org/git/data/gentoo-news.git}" \
	metadata/dtd 'Updating news'
