#!/usr/bin/env sh
set -u
only_main=+
. ${POSTSYNC_FUNCTIONS:-"${PORTAGE_CONFIGROOT-}"/etc/portage/repo.postsync.d/portage-postsyncd-mv.sh} \
	${1+"$@"}
is_git || exit 0
restart_as_default "$@"

set -- "${POSTSYNC_DAYS_NEWS:-1}" news.date metadata/news /.git
! max_days_file "$@" || exit 0
git_clone -g "${POSTSYNC_DEPTH_NEWS:-1}" \
	"${POSTSYNC_URL_NEWS:-https://anongit.gentoo.org/git/data/gentoo-news.git}" \
	"$3" 'Updating news' && update_days_file "$@"
