#!/usr/bin/env sh
set -u
only_main=+
. ${POSTSYNC_FUNCTIONS:-"${PORTAGE_CONFIGROOT-}"/etc/portage/repo.postsync.d/portage-postsyncd-mv.sh} \
	${1+"$@"}
is_git || exit 0
restart_as_default "$@"

set -- "${POSTSYNC_DAYS_GLSA:-2}" glsa.date metadata/glsa /.git
! max_days_file "$@" || exit 0
git_clone -g "${POSTSYNC_DEPTH_GLSA:-1}" \
	"${POSTSYNC_URL_GLSA:-https://anongit.gentoo.org/git/data/glsa.git}" \
	"$3" 'Updating GLSAs' && update_days_file "$@"
