#!/usr/bin/env sh
set -u
only_main=:
. ${POSTSYNC_FUNCTIONS:-"${EPREFIX-}"/lib/gentoo/repo.postsync.functions.sh} \
	${1+"$@"}
is_git || exit 0
restart_as_default "$@"

max_days_file "${POSTSYNC_DAYS_XML_SCHEMA:-30}" xml-schema.date || \
	git_clone -g "${POSTSYNC_DEPTH_XML_SCHEMA:-1}" \
	"${POSTSYNC_URL_XML_SCHEMA:-https://anongit.gentoo.org/git/data/xml-schema.git}" \
	metadata/xml-schema 'Updating xml-schema'
