#!/usr/bin/env sh
set -u
only_main=:
. ${POSTSYNC_FUNCTIONS:-"${EPREFIX-}"/lib/gentoo/repo.postsync.functions.sh} ${1+"$@"}
case $sync_uri in
*.git)
	restart_as_default "$@";;
*)
	exit 0;;
esac

max_days_file "${POSTSYNC_DAYS_DTD:-30}" dtd.date || \
	git_clone -g "${POSTSYNC_DEPTH_DTD:-1}" \
	"${POSTSYNC_URL_DTD:-https://anongit.gentoo.org/git/data/dtd.git}" \
	metadata/dtd 'Updating DTDs'
